version: '3'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  rewards_svc:
    build: .
    image: rewards_svc
    container_name: rewards_svc
    command: ./svc
    ports:
      - "7050:7050"
    depends_on:
      - mongodb
    links:
      - mongodb